version: 2

sources:
  - name: dev_silver
    database: logistics
    schema: dev_silver
    tables:
      - name: silver_customers
      - name: silver_drivers
      - name: silver_locations
      - name: silver_trips
      - name: silver_payments
      - name: silver_vehicles
