version: 2

sources:
  - name: dev_bronze                         # dbt source name
    database: logistics               # Snowflake database
    schema: dev_bronze                       # schema where bronze lives
    tables:
      - name: bronze_dim_customer
      - name: bronze_dim_store
      - name: bronze_dim_product
      - name: bronze_dim_date
      - name: bronze_fact_sales
      - name: bronze_fact_returns
